[book]
authors = ["Erik Johnston"]
language = "en"
multilingual = false
src = "src"
title = "Chat Homeserver Implementation Guide"

[output.html]
theme = "theme"
git-repository-url = "https://github.com/matrix-org/matrix.org/tree/master/implementation-guides/server"

[preprocessor.links]

[preprocessor.index]
